<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2019/10/05 01:28:04

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:dbname=qdpm;host=localhost;port=3306',
  'profiler' => false,
  'username' => 'root',
  'password' => '',
  'attributes' => 
  array (
    'quote_identifier' => true,
  ),
  'name' => 'doctrine',
)),);
