<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/10/10 08:47:08
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
