<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/10/04 19:28:56
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
