<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/10/05 11:42:11
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
