<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/10/05 11:42:20
sfConfig::add(array(
  'mod_discussionsstatus_enabled' => true,
  'mod_discussionsstatus_view_class' => 'sfPHP',
));
