<?php
// auto-generated by sfSecurityConfigHandler
// date: 2019/10/05 11:38:49
$this->security = array (
  'ldap' => 
  array (
    'is_secure' => false,
  ),
  'restorepassword' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
    'credentials' => 'allow_manage_configuration',
  ),
);
