<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/10/05 11:38:49
sfConfig::add(array(
  'mod_versionsstatus_enabled' => true,
  'mod_versionsstatus_view_class' => 'sfPHP',
));
